name: Create Testing Build

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  RELEASE_VERSION: 0.0.21

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'forge-1.20.1'
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      uses: gradle/gradle-build-action@v2.4.2
      with:
          cache-disabled: true
          arguments: build
    - name: Upload Testing Build
      uses: actions/upload-artifact@v4
      with: 
        name: greate-${{ env.RELEASE_VERSION }}-testing
        path: build/libs/*[0-9].jar
